# See Dependabot documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/packages/webview_flutter/webview_flutter_android"
    schedule:
      interval: "weekly"
    groups:
      all-github-actions:
        patterns: [ "*" ]
    reviewers:
      - "stuartmorgan"
    labels:
      - "dependencies"
      - "pub"

  # Android example apps.
  - package-ecosystem: "gradle"
    directories:
      - /packages/webview_flutter/webview_flutter/example/android/app
      - /packages/webview_flutter/webview_flutter_android/example/android/app
    commit-message:
      prefix: "[dependabot]"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "gradle"
    open-pull-requests-limit: 5
